### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by tahara2130** [Mezgrman/TweetPony#17]
I get this error
`Traceback (most recent call last):
  File "C:\Users\Nahuel\Desktop\TestTweet\TweetPony\Test - copia.py", line 22, in <module>
    main()
  File "C:\Users\Nahuel\Desktop\TestTweet\TweetPony\Test - copia.py", line 17, in main
    api.user_stream(processor = processor)
  File "C:\Python27\lib\site-packages\tweetpony\api.py", line 413, in api_call
    if processor.process_entity(entity) == False:
  File "C:\Python27\lib\site-packages\tweetpony\api.py", line 430, in process_entity
    return self.on_status(entity)
  File "C:\Users\Nahuel\Desktop\TestTweet\TweetPony\Test - copia.py", line 6, in
 on_status
    print "%s: %s" % (status.user.screen_name, status.text)
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 60-65: character maps to <undefined>`

**Comment by Carbsta** [comment]
That sounds more like a problem with python 2.7's Unicode encoding table, I am not really sure how to fix it but I know using and decoding Unicode is a widely talked about topic in python so I am sure you can find answers. Also just an FYI tweet pony is not my library, I just forked it as I was planning on taking it apart and developing it further (although I am doing other projects atm), I would suggest asking the main branch if you have problems and suggest updates to them.
