### ISSUE TITLE
Seems to be broken with Python3.6

### ISSUE THREAD

**Issue by SnowySailor** [Mezgrman/TweetPony#19]
`Traceback (most recent call last):
  File "tweeter.py", line 43, in <module>
    api = tweetpony.API(consumer_key="thingies", consumer_secret="thingies", access_token="thingies", access_token_secret="thingies")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tweetpony/api.py", line 70, in __init__
    self.user = self.verify_credentials() if self.load_user and self.access_token and self.access_token_secret else DummyUser()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tweetpony/api.py", line 406, in api_call
    resp = self.do_request("POST" if data['post'] else "GET", url, get = get_data, post = post_data, files = files, stream = stream)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tweetpony/api.py", line 160, in do_request
    header = self.get_oauth_header(method, url, callback_url, get, post)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tweetpony/api.py", line 123, in get_oauth_header
    auth_data = list(self.get_oauth_header_data(callback_url = callback_url).items())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tweetpony/api.py", line 100, in get_oauth_header_data
    'oauth_nonce': self.oauth_generate_nonce(),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tweetpony/api.py", line 95, in oauth_generate_nonce
    return base64.b64encode(hashlib.sha1(str(random.getrandbits(256))).digest(), random.choice(['rA','aZ','gQ','hH','hG','aR','DD'])).rstrip('==')
TypeError: Unicode-objects must be encoded before hashing`

**Comment by AgoraSecurity** [comment]
Hello,

I have the same problem:

tw@ubuntu:/simple$ python3 bot.py 
Traceback (most recent call last):
  File "bot.py", line 16, in <module>
    access_token_secret = u'1sfhj74zxjfsde3tsdgcF1L5....')
  File "/usr/local/lib/python3.5/dist-packages/tweetpony/api.py", line 70, in __init__
    self.user = self.verify_credentials() if self.load_user and self.access_token and self.access_token_secret else DummyUser()
  File "/usr/local/lib/python3.5/dist-packages/tweetpony/api.py", line 406, in api_call
    resp = self.do_request("POST" if data['post'] else "GET", url, get = get_data, post = post_data, files = files, stream = stream)
  File "/usr/local/lib/python3.5/dist-packages/tweetpony/api.py", line 160, in do_request
    header = self.get_oauth_header(method, url, callback_url, get, post)
  File "/usr/local/lib/python3.5/dist-packages/tweetpony/api.py", line 123, in get_oauth_header
    auth_data = list(self.get_oauth_header_data(callback_url = callback_url).items())
  File "/usr/local/lib/python3.5/dist-packages/tweetpony/api.py", line 100, in get_oauth_header_data
    'oauth_nonce': self.oauth_generate_nonce(),
  File "/usr/local/lib/python3.5/dist-packages/tweetpony/api.py", line 95, in oauth_generate_nonce
    return base64.b64encode(hashlib.sha1(str(random.getrandbits(256))).digest(), random.choice(['rA','aZ','gQ','hH','hG','aR','DD'])).rstrip('==')
TypeError: Unicode-objects must be encoded before hashing
